# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

    config.vm.box = "bento/ubuntu-22.04"
    config.vm.hostname = "xdp-DUT"
    config.vm.define "xdp-DUT"

    config.vm.network :forwarded_port, guest: 22, host: 2311, id: 'ssh'

    # config.vm.synced_folder "../data", "/vagrant_data"
  
    # config.vm.provision "shell", path: "scripts/install-libbpf.sh"
  end
  