# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|


  # Trex VM
  config.vm.define "tRex", primary: true do |trex|
    trex.vm.box = "bento/ubuntu-22.04"
    trex.vm.hostname = "tRex"

    # Private IPs
    trex.vm.network "private_network", ip: "198.18.1.11",
        virtualbox__intnet: "net1", mac: "080027112201"
    trex.vm.network "private_network", ip: "198.18.2.11",
        virtualbox__intnet: "net2", mac: "080027112202"
    # Forward Trex Ports
    trex.vm.network "forwarded_port", guest: 4500, host: 4500
    trex.vm.network "forwarded_port", guest: 4501, host: 4501
    # ssh, NAT 
    trex.vm.network "private_network", ip: "198.18.60.11"
    trex.vm.network "forwarded_port", guest: 22, host: 2211, id: 'ssh'

    trex.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
      vb.memory = "2048"
      # tRex needs min 3 cores for two interfaces
      vb.cpus = 4
    end

    trex.vm.provision "shell", path: "scripts/install-trex.sh", privileged: true

  end  
  
  # DUT VM
  config.vm.define "xdp-DUT" do |dut|
    dut.vm.box = "bento/ubuntu-22.04"
    dut.vm.hostname = "xdp-DUT"

    # private IPs 
    dut.vm.network "private_network", ip: "198.18.1.10",
        virtualbox__intnet: "net1", mac: "080027445501"
    dut.vm.network "private_network", ip: "198.18.2.10",
        virtualbox__intnet: "net2", mac: "080027445502"

    # ssh, NAT 
    dut.vm.network "private_network", ip: "198.18.60.10"
    dut.vm.network "forwarded_port", guest: 22, host: 2212, id: 'ssh'

    dut.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
      vb.memory = "2048"
      vb.cpus = 2
    end

    dut.vm.provision "shell", path: "scripts/install-tools.sh"
    dut.vm.provision "shell", path: "scripts/linux-source.sh", env: {"linux_source_dir" => "linux-5.15.0"}

  end

end
  